package com.pets.test.dao;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.annotation.Commit;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.ContextHierarchy;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.transaction.annotation.Transactional;

import com.pets.DAO.LoginRepo;
import com.pets.DTO.CreateUserDTO;
import com.pets.exception.CreationException;
import com.pets.exception.DatabaseExeption;
import com.pets.model.User;

@ExtendWith(SpringExtension.class)
@ContextHierarchy({
	@ContextConfiguration("classpath:applicationContext.xml")
})
@WebAppConfiguration
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class testLoginDAO {

	@Autowired
	private LoginRepo loginRepo;
	
	@Test
	@Transactional
	@Order(0)
//	@Commit // or @Rollback(false), functionally the same
	void testAddUser_hasAutoGeneratedId() {
		CreateUserDTO createUserDTO = new CreateUserDTO("firstName", "lastName", "username", "password", "email");
		User user = new User();
		
		try {
			user = loginRepo.createUser(createUserDTO);
		} catch (CreationException e) {
			e.printStackTrace();
		} catch (DatabaseExeption e) {
			e.printStackTrace();
		}
		
		System.out.println(user);
		
		assertTrue(user.getUser_id() != 0);
	}

}
